version: "3.8"

services:
  app:
    image: node:16-alpine
    command: sh -c "npm install && npm run start"
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MONGODB_URI: mongodb://metroroot:metroroot@172.16.253.28:27017/db_metro_logger_dev

